param(
    [ValidateSet("Release", "RelWithDebInfo", "Debug")]
    [string] $Configuration = "Release",

    [string] $Target = "REFramework",

    [switch] $Clean,
    [switch] $AllowDirty,
    [switch] $SkipSubmodules,
    [switch] $SkipCmkrGeneration,
    [switch] $SkipPackage
)

$ErrorActionPreference = "Stop"

$RepoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
$BuildDir = Join-Path $RepoRoot "build"
$CommitHeader = Join-Path $RepoRoot "src\CommitHash.autogenerated"

function Resolve-Tool {
    param(
        [string] $Name,
        [string[]] $FallbackPaths
    )

    $command = Get-Command $Name -ErrorAction SilentlyContinue

    if ($command) {
        return $command.Source
    }

    foreach ($path in $FallbackPaths) {
        if (Test-Path $path) {
            return $path
        }
    }

    throw "Could not find $Name on PATH or in known fallback locations."
}

function Invoke-Git {
    param([Parameter(ValueFromRemainingArguments = $true)][string[]] $Arguments)

    $output = & git @Arguments

    if ($LASTEXITCODE -ne 0) {
        throw "git $($Arguments -join ' ') failed with exit code $LASTEXITCODE"
    }

    return $output
}

function Invoke-CommandChecked {
    param(
        [string] $Command,
        [string[]] $Arguments
    )

    & $Command @Arguments

    if ($LASTEXITCODE -ne 0) {
        throw "$Command $($Arguments -join ' ') failed with exit code $LASTEXITCODE"
    }
}

function Add-ZipDirectory {
    param(
        [System.IO.Compression.ZipArchive] $Archive,
        [string] $EntryName
    )

    if (-not $EntryName.EndsWith("/")) {
        $EntryName = "$EntryName/"
    }

    $null = $Archive.CreateEntry($EntryName)
}

function Add-ZipFile {
    param(
        [System.IO.Compression.ZipArchive] $Archive,
        [string] $SourcePath,
        [string] $EntryName
    )

    if (-not (Test-Path $SourcePath)) {
        throw "Package source file not found: $SourcePath"
    }

    $entry = $Archive.CreateEntry($EntryName, [System.IO.Compression.CompressionLevel]::Optimal)
    $entryStream = $entry.Open()
    $sourceStream = [System.IO.File]::OpenRead($SourcePath)

    try {
        $sourceStream.CopyTo($entryStream)
    } finally {
        $sourceStream.Dispose()
        $entryStream.Dispose()
    }
}

function New-TextFileNoBom {
    param(
        [string] $Path,
        [string] $Contents
    )

    [System.IO.File]::WriteAllText($Path, $Contents, [System.Text.UTF8Encoding]::new($false))
}

Set-Location $RepoRoot

$CMake = Resolve-Tool "cmake" @(
    "C:\Program Files\CMake\bin\cmake.exe",
    "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe",
    "C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe",
    "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe",
    "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe",
    "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe"
)

$CSharpCompiler = Resolve-Tool "csc" @(
    "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\csc.exe",
    "C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\Roslyn\csc.exe",
    "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\csc.exe",
    "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Roslyn\csc.exe",
    "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Roslyn\csc.exe"
)

$NetFramework472Refs = "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2"

if (-not (Test-Path $NetFramework472Refs)) {
    throw "Missing .NET Framework 4.7.2 reference assemblies. Install the .NET Framework 4.7.2 Developer Pack/Targeting Pack, then rerun this script."
}

$gitRoot = Resolve-Path (Invoke-Git rev-parse --show-toplevel)

if ($gitRoot.Path -ne $RepoRoot.Path) {
    throw "Build script must run inside the REFramework repo root. Expected $($RepoRoot.Path), got $($gitRoot.Path)."
}

if (-not $AllowDirty) {
    $dirty = & git status --porcelain

    if ($LASTEXITCODE -ne 0) {
        throw "git status failed with exit code $LASTEXITCODE"
    }

    if ($dirty) {
        throw "Working tree is dirty. Commit/stash changes, or pass -AllowDirty for an intentionally non-release local build."
    }
}

if ($Clean -and (Test-Path $BuildDir)) {
    Remove-Item -LiteralPath $BuildDir -Recurse -Force
}

if (-not $SkipSubmodules) {
    Invoke-CommandChecked git @("submodule", "update", "--init", "--recursive")
}

$commitHash = (Invoke-Git rev-parse HEAD).Trim()
$branch = (Invoke-Git rev-parse --abbrev-ref HEAD).Trim()
$totalCommits = (Invoke-Git rev-list --count HEAD).Trim()

$tag = (& git describe --tags --abbrev=0 2>$null)
if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($tag)) {
    $tag = "no_tag"
} else {
    $tag = $tag.Trim()
}

$describeLong = (& git describe --tags --long 2>$null)
if ($LASTEXITCODE -eq 0 -and $describeLong -match "^(.*)-([0-9]+)-g[0-9a-f]+$") {
    $tagLong = $Matches[1]
    $commitsPastTag = $Matches[2]
} else {
    $tagLong = $tag
    $commitsPastTag = "0"
}

if ($env:SOURCE_DATE_EPOCH) {
    $epochSeconds = [int64]$env:SOURCE_DATE_EPOCH
} else {
    $epochSeconds = [int64](Invoke-Git show -s --format=%ct HEAD).Trim()
}

$buildDateTime = [DateTimeOffset]::FromUnixTimeSeconds($epochSeconds).UtcDateTime
$buildDate = $buildDateTime.ToString("dd.MM.yyyy")
$buildTime = $buildDateTime.ToString("HH:mm")

$commitHeaderLines = @(
    "#pragma once",
    "#define REF_COMMIT_HASH `"$commitHash`"",
    "#define REF_TAG `"$tag`"",
    "#define REF_TAG_LONG `"$tagLong`"",
    "#define REF_COMMITS_PAST_TAG $commitsPastTag",
    "#define REF_BRANCH `"$branch`"",
    "#define REF_TOTAL_COMMITS $totalCommits",
    "#define REF_BUILD_DATE `"$buildDate`"",
    "#define REF_BUILD_TIME `"$buildTime`""
)

[System.IO.File]::WriteAllLines($CommitHeader, $commitHeaderLines, [System.Text.UTF8Encoding]::new($false))

$configureArgs = @(
    "-S", $RepoRoot.Path,
    "-B", $BuildDir,
    "-G", "Visual Studio 17 2022",
    "-A", "x64",
    "-DDEVELOPER_MODE=ON",
    "-DCMAKE_BUILD_TYPE=$Configuration",
    "-DCMAKE_POLICY_VERSION_MINIMUM=3.5",
    "-DCMAKE_CSharp_COMPILER=$($CSharpCompiler.Replace('\', '/'))"
)

if ($SkipCmkrGeneration) {
    $configureArgs += "-DCMKR_SKIP_GENERATION=ON"
}

Invoke-CommandChecked $CMake $configureArgs

$buildArgs = @(
    "--build", $BuildDir,
    "--config", $Configuration,
    "--target", $Target,
    "--parallel"
)

Invoke-CommandChecked $CMake $buildArgs

$outputDir = Join-Path $BuildDir "bin\REFramework"
Write-Host "Built target '$Target' ($Configuration) in $BuildDir"
Write-Host "Expected REFramework output folder: $outputDir"

if (-not $SkipPackage -and $Target -eq "REFramework") {
    Add-Type -AssemblyName System.IO.Compression
    Add-Type -AssemblyName System.IO.Compression.FileSystem

    $packageDir = Join-Path $BuildDir "package\RE7"
    $zipPath = Join-Path $BuildDir "RE7.zip"
    $openxrLoader = Join-Path $BuildDir "_deps\openxr-build\src\loader\$Configuration\openxr_loader.dll"
    $openvrApi = Join-Path $BuildDir "bin\openvr_api.dll"
    $dinput = Join-Path $outputDir "dinput8.dll"
    $revisionFile = Join-Path $packageDir "reframework_revision.txt"
    $openxrMarker = Join-Path $packageDir "DELETE_OPENVR_API_DLL_IF_YOU_WANT_TO_USE_OPENXR"

    if (Test-Path $packageDir) {
        Remove-Item -LiteralPath $packageDir -Recurse -Force
    }

    New-Item -ItemType Directory -Force -Path $packageDir | Out-Null
    New-TextFileNoBom $revisionFile "$commitHash`r`n"
    New-TextFileNoBom $openxrMarker "none`r`n"

    if (Test-Path $zipPath) {
        Remove-Item -LiteralPath $zipPath -Force
    }

    $zip = [System.IO.Compression.ZipFile]::Open($zipPath, [System.IO.Compression.ZipArchiveMode]::Create)

    try {
        Add-ZipFile $zip $openxrMarker "DELETE_OPENVR_API_DLL_IF_YOU_WANT_TO_USE_OPENXR"
        Add-ZipFile $zip $dinput "dinput8.dll"
        Add-ZipFile $zip $openvrApi "openvr_api.dll"
        Add-ZipFile $zip $openxrLoader "openxr_loader.dll"
        Add-ZipDirectory $zip "reframework/autorun"

        foreach ($script in @(
            "re2_sharpness_removal.lua",
            "re2_smooth_movement.lua",
            "re2_vr_crosshair.lua",
            "re2_vr_grenade.lua",
            "re2_vr_melee.lua",
            "re4_vr_crosshair.lua",
            "re8_vr.lua"
        )) {
            Add-ZipFile $zip (Join-Path $RepoRoot "scripts\$script") "reframework/autorun/$script"
        }

        Add-ZipDirectory $zip "reframework/autorun/utility"

        foreach ($script in @(
            "GameObject.lua",
            "ManagedObjectDict.lua",
            "RE2.lua",
            "RE4.lua",
            "RE7.lua",
            "RE8.lua",
            "Statics.lua"
        )) {
            Add-ZipFile $zip (Join-Path $RepoRoot "scripts\utility\$script") "reframework/autorun/utility/$script"
        }

        Add-ZipDirectory $zip "reframework/autorun/vr"
        Add-ZipFile $zip (Join-Path $RepoRoot "scripts\vr\VRControllerManager.lua") "reframework/autorun/vr/VRControllerManager.lua"
        Add-ZipFile $zip $revisionFile "reframework_revision.txt"
    } finally {
        $zip.Dispose()
    }

    Write-Host "Packaged RE7 release zip: $zipPath"
}
