name: RE7 TDB49 Dev Release

on: [push, workflow_dispatch]

env:
  BUILD_TYPE: Release

jobs:
  re7-tdb49-release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -G "Visual Studio 17 2022" -A x64 -DDEVELOPER_MODE=ON -DCMKR_SKIP_GENERATION=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target RE7

      - name: Package release
        shell: pwsh
        run: .\dev\package-re7-tdb49.ps1 -BuildDir ${{github.workspace}}\build -Configuration ${{env.BUILD_TYPE}} -OutputDir ${{github.workspace}}\build\release

      - name: Upload artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: RE7_TDB49
          path: ${{github.workspace}}/build/release/RE7_TDB49.zip
          if-no-files-found: error

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
